export const themes = {
    light: {
        id: 'light',
        name: 'Light Mode',
        colors: {
            '--bg-primary': '#f8fafc',
            '--bg-secondary': '#ffffff',
            '--bg-card': '#ffffff',
            '--bg-hover': '#f1f5f9',
            '--text-primary': '#0f172a',
            '--text-secondary': '#475569',
            '--text-muted': '#94a3b8',
            '--text-on-primary': '#ffffff',
            '--primary': '#6366f1',
            '--primary-hover': '#4f46e5',
            '--primary-light': '#e0e7ff',
            '--border': '#e2e8f0',
            '--border-light': '#f1f5f9',
            '--shadow-sm': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
            '--shadow-md': '0 4px 6px -1px rgb(0 0 0 / 0.1)',
            '--success': '#10b981',
            '--success-bg': '#d1fae5',
            '--success-text': '#065f46',
            '--warning': '#f59e0b',
            '--warning-bg': '#fef3c7',
            '--warning-text': '#92400e',
            '--danger': '#ef4444',
            '--danger-bg': '#fee2e2',
            '--danger-text': '#991b1b',
            '--info': '#3b82f6',
            '--info-bg': '#dbeafe',
            '--info-text': '#1e40af'
        }
    },
    dark: {
        id: 'dark',
        name: 'Dark Mode',
        colors: {
            '--bg-primary': '#0f172a',
            '--bg-secondary': '#1e293b',
            '--bg-card': '#1e293b',
            '--bg-hover': '#334155',
            '--text-primary': '#f8fafc',
            '--text-secondary': '#94a3b8',
            '--text-muted': '#64748b',
            '--text-on-primary': '#ffffff',
            '--primary': '#6366f1',
            '--primary-hover': '#818cf8',
            '--primary-light': '#312e81',
            '--border': '#334155',
            '--border-light': '#1e293b',
            '--shadow-sm': '0 1px 2px 0 rgb(0 0 0 / 0.5)',
            '--shadow-md': '0 4px 6px -1px rgb(0 0 0 / 0.5)',
            '--success': '#10b981',
            '--success-bg': '#064e3b',
            '--success-text': '#d1fae5',
            '--warning': '#f59e0b',
            '--warning-bg': '#78350f',
            '--warning-text': '#fef3c7',
            '--danger': '#ef4444',
            '--danger-bg': '#7f1d1d',
            '--danger-text': '#fee2e2',
            '--info': '#3b82f6',
            '--info-bg': '#1e3a8a',
            '--info-text': '#dbeafe'
        }
    },
    ocean: {
        id: 'ocean',
        name: 'Ocean Blue',
        colors: {
            '--bg-primary': '#0B1120',
            '--bg-secondary': '#152038',
            '--bg-card': '#152038',
            '--bg-hover': '#1e2d4d',
            '--text-primary': '#e2e8f0',
            '--text-secondary': '#94a3b8',
            '--text-muted': '#64748b',
            '--text-on-primary': '#ffffff',
            '--primary': '#0ea5e9',
            '--primary-hover': '#38bdf8',
            '--primary-light': '#0c4a6e',
            '--border': '#1e293b',
            '--border-light': '#0f1729',
            '--shadow-sm': '0 1px 2px 0 rgb(0 0 0 / 0.5)',
            '--shadow-md': '0 4px 6px -1px rgb(0 0 0 / 0.5)',
            '--success': '#22d3ee',
            '--success-bg': '#164e63',
            '--success-text': '#cffafe',
            '--warning': '#fbbf24',
            '--warning-bg': '#78350f',
            '--warning-text': '#fef3c7',
            '--danger': '#f43f5e',
            '--danger-bg': '#881337',
            '--danger-text': '#ffe4e6',
            '--info': '#3b82f6',
            '--info-bg': '#1e3a8a',
            '--info-text': '#dbeafe'
        }
    },
    forest: {
        id: 'forest',
        name: 'Forest Green',
        colors: {
            '--bg-primary': '#052e16',
            '--bg-secondary': '#14532d',
            '--bg-card': '#14532d',
            '--bg-hover': '#166534',
            '--text-primary': '#ecfccb',
            '--text-secondary': '#a3e635',
            '--text-muted': '#65a30d',
            '--text-on-primary': '#000000',
            '--primary': '#bef264',
            '--primary-hover': '#d9f99d',
            '--primary-light': '#365314',
            '--border': '#166534',
            '--border-light': '#14532d',
            '--shadow-sm': '0 1px 2px 0 rgb(0 0 0 / 0.5)',
            '--shadow-md': '0 4px 6px -1px rgb(0 0 0 / 0.5)',
            '--success': '#4ade80',
            '--success-bg': '#14532d',
            '--success-text': '#dcfce7',
            '--warning': '#facc15',
            '--warning-bg': '#713f12',
            '--warning-text': '#fef9c3',
            '--danger': '#f87171',
            '--danger-bg': '#7f1d1d',
            '--danger-text': '#fecaca',
            '--info': '#60a5fa',
            '--info-bg': '#1e3a8a',
            '--info-text': '#dbeafe'
        }
    },
    sunset: {
        id: 'sunset',
        name: 'Sunset Purple',
        colors: {
            '--bg-primary': '#2e1065',
            '--bg-secondary': '#4c1d95',
            '--bg-card': '#4c1d95',
            '--bg-hover': '#5b21b6',
            '--text-primary': '#fae8ff',
            '--text-secondary': '#d8b4fe',
            '--text-muted': '#a855f7',
            '--text-on-primary': '#ffffff',
            '--primary': '#f472b6',
            '--primary-hover': '#f9a8d4',
            '--primary-light': '#831843',
            '--border': '#5b21b6',
            '--border-light': '#4c1d95',
            '--shadow-sm': '0 1px 2px 0 rgb(0 0 0 / 0.5)',
            '--shadow-md': '0 4px 6px -1px rgb(0 0 0 / 0.5)',
            '--success': '#34d399',
            '--success-bg': '#064e3b',
            '--success-text': '#d1fae5',
            '--warning': '#fbbf24',
            '--warning-bg': '#78350f',
            '--warning-text': '#fef3c7',
            '--danger': '#f471b6',
            '--danger-bg': '#831843',
            '--danger-text': '#fce7f3',
            '--info': '#818cf8',
            '--info-bg': '#312e81',
            '--info-text': '#e0e7ff'
        }
    },
    rose: {
        id: 'rose',
        name: 'Rose Gold',
        colors: {
            '--bg-primary': '#fff1f2',
            '--bg-secondary': '#ffffff',
            '--bg-card': '#ffffff',
            '--bg-hover': '#ffe4e6',
            '--text-primary': '#881337',
            '--text-secondary': '#be123c',
            '--text-muted': '#9f1239',
            '--text-on-primary': '#ffffff',
            '--primary': '#e11d48',
            '--primary-hover': '#be123c',
            '--primary-light': '#ffe4e6',
            '--border': '#fecdd3',
            '--border-light': '#fff1f2',
            '--shadow-sm': '0 1px 2px 0 rgb(136 19 55 / 0.1)',
            '--shadow-md': '0 4px 6px -1px rgb(136 19 55 / 0.1)',
            '--success': '#10b981',
            '--success-bg': '#d1fae5',
            '--success-text': '#065f46',
            '--warning': '#f59e0b',
            '--warning-bg': '#fef3c7',
            '--warning-text': '#92400e',
            '--danger': '#e11d48',
            '--danger-bg': '#fee2e2',
            '--danger-text': '#881337',
            '--info': '#3b82f6',
            '--info-bg': '#dbeafe',
            '--info-text': '#1e40af'
        }
    }
};
